### ISSUE TITLE
Conduit project to be published with SPA and served via IIS

### ISSUE THREAD

**Issue by m2017atTR** [kdcllc/aspnetcore-angular-realworld-example-app#2]
When i tryed to publish via Visual Studio 2017 
needed to add @angular-devkit/build-optimizer

When i published to IIS at /spa route i get 
{"errors":"InternalServerError"}

there is nothing at Windows log...

Where to look and how to solve

**Comment by kdcllc** [comment]
@m2017atTR, please get the latest on master branch. I patched the issue.

https://github.com/kdcllc/aspnetcore-angular-realworld-example-app/tree/a7381fc97cc335fb4fe0436034ac2625db7c5330
